version: '3.8'

services:
  # 1. 백엔드 개발 환경
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app
      - ./shared_uploads:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env  # 백엔드도 .env를 읽어서 DB에 접속합니다.

    environment:
      - AI_PROXY_URL=http://ai:8001

    networks:
      - platform-network

  # 2. AI 중계 서버 개발 환경 (이하 기존과 동일)
  ai:
    build:
      context: ./ai
    volumes:
      - ./ai/app:/app/app
      - ./shared_uploads:/app/uploads
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - platform-network
    # AI 모델 로딩으로 인해 메모리 부족(OOM)으로 꺼질 경우 자동 재시작
    restart: unless-stopped

  # 3. 프론트엔드 개발 환경
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env  # 프론트도 .env를 읽기.
        # 빌드할 때 환경 변수 이름을 바꿔서 주입
    # 환경 변수의 이름을 바꿔 넣기
    environment:
      - WATCHPACK_POLLING=true    # (Hot Reload) 웹팩 폴링 활성화
      - CHOKIDAR_USEPOLLING=true  # (Hot Reload) 파일 감시자 폴링 활성화
      - REACT_APP_KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
      - REACT_APP_FRONTEND_URL=${FRONTEND_URL}


    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true
    networks:
      - platform-network
    depends_on:
      - backend  # 백엔드가 뜬 후 실행

networks:
  platform-network:
    driver: bridge